### ISSUE TITLE
Stucked on Uhans logo after successfull instalation of TWRP

### ISSUE THREAD

**Issue by mauriciofaria** [almasen/twrp_android_device_uhans_s1#1] opened 2019-11-01 11:16 UTC
I was able to install TWRP and it works fine.
But when I boot the device it stucks at Uhans logo and do nothing...
I am able to enter TWRP and do everything.
Cache wipe didn't help.
Data, Cache and Dalvik wipe didn't help.

**Comment by almasen** [comment] 2019-11-05 01:39
Hi mauriciofaria,

So sorry about your troubles caused by having installed this recovery image, this is the first time I heard someone get their device bricked from this recovery flash.

Did you just unlock your bootloader when installing TWRP, or had it been unlocked before? i.e. after your bootloader got unlocked, did you still manage to boot your phone?

To fix your bootloop, do you have a stock firmware image that you could install on your device?

**Comment by mauriciofaria** [comment] 2019-11-05 11:09
Hi almasen.
I managed to recover the phone, reinstalling the original firmware via Sp FLash Tools.
Then I tried again... :)
Can't remember all I did, but I will try to explain...
After a successful installation and the second boot into the system I copied a ZIP with SuperSU and when I booted the recovery again to install the app it was overwrited with the original one. Weird.
Since I was able to boot one time and go back to the recovery, I copied the zip in the first boot and than was able to boot TWRP and install SuperSU.
But the device didn't boot anymore, it was stucked at the logo.
I did it again and I was stucked again.
So, I installed TWRP, copied the SuperSU to the device in the first boot, booted to TWRP, installed SuperSU, turned the device off, reinstalled, via SP Flash Tools, the official ROM except the system partition.
This time it booted ok and SuperSU was installed and functional !
And since I only needed root access, for me it is fine.
I am using the phone for a few days and everything seems ok.
And every time I boot, a message stating that the device was dangerously hacked is displayed. :)
As I said, I can't be sure all the events I did with the device, because I played a lot, but the last sequence was for sure.
It is possible that this is related with the firmware version, I wasn't using the version that came with the phone, that was 3.09.  I was using a 3.12 version I found a year ago in the internet. And the 3.12 was the one I did all this stuff.
 
[[]] Maurício

**Comment by mauriciofaria** [comment] 2019-11-05 13:11
> Did you just unlock your bootloader when installing TWRP, or had it been unlocked before? i.e. after your bootloader got unlocked, did you still manage to boot your phone?
 
It was already unlocked, probably I did it before trying another way to root the phone.

**Comment by almasen** [comment] 2019-11-07 17:15
Hey there,

I am very glad you managed to resolve the issue! 
Great job, and thanks for letting me know the steps you have taken, 

> So, I installed TWRP, copied the SuperSU to the device in the first boot, booted to TWRP, installed SuperSU, turned the device off, reinstalled, via SP Flash Tools, the official ROM except the system partition.

I guess this is the part that did the trick.


> I booted the recovery again to install the app it was overwrited with the original one. Weird.

I noted this in my guide, maybe not explicitely enough, that it can overwrite with the original during it's boot process. That's why it is recommended that instead of letting it boot, you just go straight to recovery.

> It is possible that this is related with the firmware version, I wasn't using the version that came with the phone, that was 3.09. I was using a 3.12 version I found a year ago in the internet. And the 3.12 was the one I did all this stuff.

&

> It was already unlocked, probably I did it before trying another way to root the phone. 

I find it unlikely that the different firmware was the cause of the issue, as I have tested this from 3.0 beta to 3.12 and it worked. I think it is more likely that having tried those _aternative_ root options led to the bootloop - as this is exactly what happened to a lot of people and why I released this recovery, so people are able to do a clean root with recovery. 

I have now had a bit of time, tested two of these _super, one click root options_ and then installed superSU, and both led to a bricked phone. So, thank you very much for bringing my attention to this, I will maybe add a warning to the guide about these.

>  And every time I boot, a message stating that the device was dangerously hacked is displayed. :)

Yeah, I noted the funny warning in the readme 😄 

> 2.3 On a successful installation you should see the TWRP logo show up and a prompt related to unlocking the device.


Anyways, I am very glad you now have a working device with TWRP and a proper root solution!

One thing to note is that since you have done a couple of reinstalls with a build found online, please **do make sure to double check you are not running a version with preinstalled malware**. A lot of firmware versions circulating online also had the preinstalled fake YouTube app. 
Don't worry though, you probably would have been notified by now in such case, as Google Play Protect detects most of them lately, but running a [Virustotal](https://play.google.com/store/apps/details?id=com.funnycat.virustotal) scan cannot hurt...and this app is very useful anyways.

Should you be also intersted in Xposed or some similar other extras, I am just letting you know that I have found working versions of these as well. But **please always make a Nandroid backup with TWRP** if you make risky changes in the future. This way you can just restore everything in a click.

I'll now close this issue.

Best wishes,
Daniel

**Closed as completed by almasen** 2019-11-07 17:15 UTC

**Comment by allexis-rapo** [comment] 2020-05-03 16:18
Hi almasem,
I installed twrp about steps, first unlocked is "yes", and flash was "ok", but when reboot recovery this step, I see a message "Sin comandos"

**Comment by almasen** [comment] 2020-05-04 14:31
> 
> 
> Hi almasem,
> I installed twrp about steps, first unlocked is "yes", and flash was "ok", but when reboot recovery this step, I see a message "Sin comandos"

Hi allexis-rapo,

Sorry to hear you faced issues with the installation.
Do you maybe see "Sin commandos" as in the no command screen?
![maxresdefault](https://user-images.githubusercontent.com/47671879/80976198-09ecda80-8e1b-11ea-8603-f007b85f9389.jpg)
If yes, try and long `press Volume + Up` OR `press Volume Up + Power Button`. 
Does this work? 

This should not be required with TWRP so _I think you still have the stock Uhans recovery_ for some reason. 

If you do not have TWRP working, please try the following:

1. Go to `fastboot mode`
2. Type `fastboot getvar unlocked`

If you see `unlocked: yes` please try again the flashing steps from [here](https://github.com/almasen/twrp_android_device_uhans_s1#2-flashing).
If `unlocked: no` is the result, you should try the unlocking process again from [step 1.4](https://github.com/almasen/twrp_android_device_uhans_s1#1-unlocking).

Let me know if this helped.
